# Generated by Django 4.0.5 on 2022-07-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('mileage_rate', models.BigIntegerField()),
                ('value', models.FloatField()),
                ('plate_1', models.CharField(max_length=50)),
                ('plate_2', models.CharField(max_length=50)),
                ('plate_3', models.CharField(max_length=50)),
                ('plate_4', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('rental_time', models.IntegerField()),
                ('rental_daily_rate', models.FloatField()),
                ('deposit_amount', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('delivery_location', models.CharField(max_length=50)),
                ('return_location', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('desc', models.CharField(max_length=200)),
                ('rent_status', models.CharField(choices=[('R', 'Request'), ('I', 'In Rent'), ('E', 'Expired'), ('D', 'Denied'), ('P', 'Pending')], default='R', max_length=2)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarentApp.rentalcar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
